spring:
  datasource:
    url: jdbc:mysql://47.104.158.128:3306/delame?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
        show-sql: true
      database: mysql
      open-in-view: true
  resources:
      static-locations: classpath:/META-INF/resources,classpath:/resources,classpath:/static,classpath:/public
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 60s
    jedis:
      pool:
        max-idle: 100
        min-idle: 50
        max-wait: -1s
        max-active: -1
server:
  port: 8088

