spring:
  datasource:
    url: jdbc:mysql://47.104.158.128:3306/ame?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
        show-sql: true
      database: mysql