spring:
  datasource:
    url: jdbc:mysql://10.16.201.110:306/ame?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
        show-sql: true
      database: mysql
      open-in-view: true
  resources:
      static-locations: classpath:/META-INF/resources,classpath:/resources,classpath:/static,classpath:/public